rules:
  unpinned-uses:
    ignore:
      - linting.yaml
      - testing.yaml
      - publishing.yaml
  anonymous-definition:
    ignore:
      - 'linting.yaml:22'
      - 'testing.yaml:20'
      - 'testing.yaml:50'
      - 'publishing.yaml:24'
      - 'publishing.yaml:45'
      - 'publishing.yaml:61'
  undocumented-permissions:
    ignore:
      - 'publishing.yaml:70'
