name: Linting
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
  push:
    branches:
      - main
    paths-ignore:
      - docs/**

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
env:
  PY_VERSION: '3.10'
permissions: {}

jobs:
  prek:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v8.3.2
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install project
        run: uv sync --locked --dev --all-extras --managed-python
      - name: Run prek
        run: uv run prek run -a
